version: '3'
services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    environment:
      - database__client:"mysql"
      - database__connection__host:"db"
      - database__connection__user:"root"
      - database__connection__password:"senha123"
      - database__connection__database:"ghost"
    depends_on:
      - db
    restart: always
  db:
    platform: linux/amd64
    image: mysql:5.7.40
    environment:
      - MYSQL_ROOT_PASSWORD:"senha123"
    restart: always
